name: repository
description: The all-in-one solution for fetching remote data from a REST API using the power of caching and auto refresh.
version: 3.0.0+1

environment:
  sdk: ">=3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0

dependencies:
  collection: ^1.17.0
  crypto: ^3.0.2
  equatable: ^2.0.5
  hive: ^2.2.3
  http: ^0.13.5
  logging: ^1.1.1
  meta: ^1.8.0
  retry: ^3.1.1
  rxdart: ^0.27.7
